runtime: nodejs18
env: standard
automatic_scaling:
  min_idle_instance: 1
  max_idle_instance: automatic
  min_pending_latency: automatic
  max_pending_latency: automatic
includes:
  - env_variables.yaml