name: Deploy to Cloud Run
on:
  push:
    branches:
      - main
env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  RUN_REGION: asia-southeast2
  SA_KEY_JSON: ${{ secrets.GCP_SA_KEY_JSON }}
  REPO_NAME: ${{ secrets.GCP_ARTIFACT_NAME }}
jobs:
  deploy:
    name: Deploy to Cloud Run
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Setup gcloud CLI
      - uses: 'google-github-actions/setup-gcloud@v1'
        with:
          version: '>= 363.0.0'
          service_account_key: ${{ secrets.GCP_SA_KEY_JSON }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      # Build and push image to Google Container Registry
      - name: Build
        run: gcloud builds submit --tag asia-southeast2-docker.pkg.dev/$PROJECT_ID/$REPO_NAME/kjaga-backend-image:$GITHUB_SHA
        
      - name: Deploy
        run: gcloud run deploy kjaga-dev --image asia-southeast2-docker.pkg.dev/$PROJECT_ID/$REPO_NAME/kjaga-backend-image:$GITHUB_SHA --platform managed --region $RUN_REGION
